version: "3.9"
services:
  client:
    build: ./app
    container_name: rick-and-morty-graphs-and-stuff
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
