name: Trigger QA Hub (Rick & Morty)

on:
  push:
    branches: [main]

jobs:
  notify-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to QA Hub
        env:
          GH_TOKEN: ${{ secrets.QA_HUB_PAT }}
        run: |
          curl -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/allanfoppa/ai-qa-testing-hub/dispatches \
          -d '{
            "event_type": "run-rick-and-morty-graphs-and-stuff-frontend-tests",
            "client_payload": {
              "repo": "${{ github.repository }}",
              "workspace_name": "@hub/rick-and-morty-graphs-and-stuff-frontend",
              "rootPath": "app",
              "build": "npm run build",
              "start": "npm run start",
              "port": "3000"
            }
          }'
