name: Trigger QA Hub

on:
  push:
    branches: [main]

jobs:
  notify-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to QA Hub
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.QA_HUB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/allanfoppa/ai-qa-testing-hub/dispatches \
          -d '{
            "event_type": "run-rick-and-morty-graphs-and-stuff-frontend-tests",
            "client_payload": {
              "project_id": "rick-and-morty-graphs-and-stuff",
              "workspace_name": "@hub/rick-and-morty-graphs-and-stuff",
              "repo": "allanfoppa/rick-and-morty-graphs-and-stuff",
              "root_path": "app",
              "port": 3000,
              "build_script": "build",
              "start_command": "pnpm run start",
              "wait_condition": "http://127.0.0.1:$PORT"
            }
          }'
